### ISSUE TITLE
 [06/06/2020] Saturday 9:00 PM GMT+2 Data Augmentation techniques for NLP

### ISSUE THREAD

**Issue by ibrahimsharaf** [eg-nlp-community/nlp-reading-group#15]
Please join us in our discussion of "Data Augmentation techniques for NLP" on Saturday at 9:00 pm GMT+2.
Survey post: https://amitness.com/2020/05/data-augmentation-for-nlp/

**Comment by hadyelsahar** [comment]
Good comprehensive survey of hacks for data augmentation in NLP. Although each are really application dependent, and objective dependent (robustness or generalization)? 

Another techniques that hasn't been mentioned in this survey and widely used in domain adaptation is:
- Distant supervision (widely used for relation extraction) e.g. https://www.aclweb.org/anthology/P09-1113/
- self training with ensemble models widely used for domain adaptation (tri training ..etc) e.g. https://arxiv.org/pdf/1804.09530.pdf
- self distillation e.g. https://arxiv.org/abs/2002.05715
